blank_issues_enabled: true
contact_links:
  - name: FAQ & Troubleshooting
    url: https://tallysavestheinternet.com/faq
    about: Read Frequently Asked Questions about Tally Saves the Internet
  - name: How to Play
    url: https://tallysavestheinternet.com/how-to-play
    about: How does one play Tally Saves the Internet?
